version: "3.9"

services:
  qdrant:
    restart: unless-stopped
    image: qdrant/qdrant:v1.2.2
    environment:
      - QDRANT_HOST_PORT=${QDRANT_HOST_PORT}
    ports:
    - ${QDRANT_HOST_PORT}:6333
    volumes:
      - ./data/qdrant_storage:/qdrant/storage
    env_file:
      - .env   
  


